Subindo aplicação
FidelisSantos/ExercicioCadastro pull request #1
Opened 2022-11-29 19:44 UTC by FidelisSantos

2022-11-29 19:44 UTC, FidelisSantos commented
![](https://github.trello.services/images/mini-trello-icon.png) [EXERCICIO JAVASCRIPT](https://trello.com/c/gCWpuDPg/142-exercicio-javascript)

2022-12-05 21:37 UTC, LuizinhoF commented on Js/date.js
> +  var dateFormatter = formatter.format(myDate);
pq esse é var e os outros são let?

2022-12-05 21:38 UTC, LuizinhoF commented on Js/date.js
> +  let bday = new Date(date);
o que significa "bday"?

2022-12-05 21:39 UTC, LuizinhoF commented on Js/date.js
> +    var message = "Parabéns seu aniversário é hoje.";
declarar variáveis condicionalmente é estranho, ainda mais quando é a mesma variável.
Favor declarar o message antes do bloco IF e inserir o valor de acordo com a condicional.

2022-12-05 21:41 UTC, LuizinhoF commented on Js/searchCep.js
> +        city: () => {
pq aqui vc usou arrow function mas no método anterior usou uma function tradicional?
Se não houver motivo fazer manter um padrão(preferêncialmente com arrow functions)

2022-12-05 21:42 UTC, LuizinhoF commented on Js/searchCep.js
> +                console.log("entrei validação cidade")
console.log perdido

2022-12-05 21:43 UTC, LuizinhoF commented on Js/searchCep.js
> +    console.log("entrei validação cidade")
console.log perdido

2022-12-05 21:45 UTC, LuizinhoF commented on Js/searchCep.js
> +        const cityInput = document.getElementById('city');
identação

2022-12-05 21:45 UTC, LuizinhoF commented on Js/searchCep.js
> +        const adressInput = document.getElementById('adress');
identação

2022-12-05 21:45 UTC, LuizinhoF commented on Js/searchCep.js
> +    console.log("entrei validação Endereço")
console.log

2022-12-05 21:47 UTC, LuizinhoF commented on Js/template.js
> +    console.log(state);
console.log

2022-12-05 21:47 UTC, LuizinhoF commented on Js/template.js
> +        let finish = `
identação

2022-12-05 22:44 UTC, FidelisSantos commented
![](https://github.trello.services/images/mini-trello-icon.png) [EXERCICIO JAVASCRIPT](https://trello.com/c/gCWpuDPg/142-exercicio-javascript)

2022-12-05 22:44 UTC, FidelisSantos commented
![](https://github.trello.services/images/mini-trello-icon.png) [EXERCICIO JAVASCRIPT](https://trello.com/c/gCWpuDPg/142-exercicio-javascript)

2022-12-05 23:38 UTC, FidelisSantos commented
![](https://github.trello.services/images/mini-trello-icon.png) [EXERCICIO JAVASCRIPT](https://trello.com/c/gCWpuDPg/142-exercicio-javascript)

2022-12-05 23:38 UTC, FidelisSantos commented
![](https://github.trello.services/images/mini-trello-icon.png) [EXERCICIO JAVASCRIPT](https://trello.com/c/gCWpuDPg/142-exercicio-javascript)

2022-12-07 15:21 UTC, Thiagoojtds requested changes

2022-12-07 15:21 UTC, Thiagoojtds commented on Js/date.js
> +  var one_day = 24 * 60 * 60 * 1000;
vc ta usando camel case em várias variáveis, e aqui usou snake, acho melhor seguir nesse padrão

2022-12-07 15:21 UTC, Thiagoojtds commented on Js/script.js
> +    $('#dice-tab').tab('show');
esse dice-tab quer dizer dado de um jogo, e não dados de um usuário, o correto seria utilizar data-tab ou coisa assim

2022-12-07 15:21 UTC, Thiagoojtds commented on Js/searchCep.js
> +export function validateState(state) {
não entendi pq vc criou um método pra validar cada campo, se você faz essa validação já quando recebe o resultado da api no método validateCEP(), também não encontrei onde você chamou esses métodos de validação

2022-12-07 15:21 UTC, Thiagoojtds commented on Js/validate.js
> +    let month = today.getMonth() - bday.getMonth();
pq ta usando let nessas variáveis e as outras são const?

2022-12-07 15:21 UTC, Thiagoojtds commented on Js/validate.js
> +            let status = (name.value !== '' && !regex.test(name.value));
você ta redeclarando essa variável status vairias vezes em cada função, pode delcarar antes e ir só atribuindo o valor, como fez com error

2022-12-07 15:21 UTC, Thiagoojtds commented on Js/validate.js
> +            let status = (adress.value !== '');
mesma coisa aqui

2022-12-07 15:21 UTC, Thiagoojtds commented on Js/validate.js
> +    soma += cpf[9] * 2;
pode mudar pra um for essa repetição q fica mais clean em kkkk

2022-12-08 13:56 UTC, Henriquenascimento01 commented on Js/searchCep.js
> +    const searchQuery = search.value;
aqui não daria pra ter pego o valor do campo 'search' na primeira vez, ao invés de pegar o id e depois atribuir o valor em outra variável ?

2022-12-08 13:56 UTC, Henriquenascimento01 commented on Js/template.js
> +    const div = document.querySelector('#end');
o que seria 'div' ?

2022-12-08 14:03 UTC, MauricioBarbosa requested changes

2022-12-08 14:03 UTC, MauricioBarbosa commented on Js/date.js
> +  let myDate = new Date(date);
Esse nome "myDate" fica estranho, nomes de variáveis devem descrever o que elas são 

acho que compensa mais alterar o nome da variável de cima para "documentDate" ou algo que a relacione ao seu input de date, e aí sim, mudar o nome da variável de baixo para date

2022-12-08 14:03 UTC, MauricioBarbosa commented on Js/date.js
> +  var dateFormatter = formatter.format(myDate);
Evitar usar var, é uma prática ruim. 

Usar apenas const(para variáveis que não mudam) e let(para variáveis que mudam) 

https://blog.lsantos.dev/mas-praticas-javascript/

2022-12-08 14:03 UTC, MauricioBarbosa commented on Js/date.js
> +  let upcomingBday = new Date(today.getFullYear(), bday.getMonth(), bday.getDate());
o que é upcomingBDay? seja claro no nome das variáveis

2022-12-09 19:28 UTC, Thiagoojtds approved these changes

2022-12-09 20:36 UTC, merged